apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: create-prod-workload
  title: Create production workload for application
  description: Golden path to create argocd workload for application to be able to deploy in production
  tags:
    - argocd
    - workload
    - goldenpath
  links:
    - url: https://gitea.134.209.138.125.nip.io/otomi/backstage/src/branch/master/software-templates/create-workload.yaml
      title: Gitea
      icon: location
      type: Gitea
    - url: https://backstage.io/docs/features/software-templates/writing-templates/
      title: Docs
      icon: techdocs
      type: Documentation
spec:
  owner: platform team
  type: Golden path

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Service name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the application
          ui:autofocus: true
          ui:options:
            rows: 5

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    - id: update-pipeline
      name: Update pipeline
      action: publish:pipeline
      input:
        name: ${{ parameters.name }}
        environment: prod
  
    - id: create-deployment
      name: Create prod deployment file
      action: publish:deployment
      input:
        name: ${{ parameters.name }}
        environment: prod
  
    - id: create-service
      name: Create prod service file
      action: publish:service
      input:
        name: ${{ parameters.name }}
        environment: prod
    
    - id: create-service
      name: Create prod servicemonitor file
      action: publish:serviceMonitor
      input:
        name: ${{ parameters.name }}
        environment: prod
  
    - id: create-workload
      name: Update applicationset
      action: publish:workload
      input:
        name: ${{ parameters.name }}
        environment: prod
  
  output:
    links:
      - title: GitOps repository
        url: 'https://gitea.134.209.138.125.nip.io/otomi/argo-workload'
      - title: ArgoCD service
        url: 'https://argocd.134.209.138.125.nip.io/applications/argocd/services?view=tree&resource='